V3.MEAN.RAW.URL <- "ftp://ftp.ncdc.noaa.gov/pub/data/ghcn/v3/ghcnm.tavg.latest.qcu.tar.gz"
V3.MEAN.ADJ.URL <- "ftp://ftp.ncdc.noaa.gov/pub/data/ghcn/v3/ghcnm.tavg.latest.qca.tar.gz"
V3.TMAX.RAW.URL <- "ftp://ftp.ncdc.noaa.gov/pub/data/ghcn/v3/ghcnm.tmax.latest.qcu.tar.gz"
V3.TMAX.ADJ.URL <- "ftp://ftp.ncdc.noaa.gov/pub/data/ghcn/v3/ghcnm.tmax.latest.qca.tar.gz"
V3.TMIN.RAW.URL <- "ftp://ftp.ncdc.noaa.gov/pub/data/ghcn/v3/ghcnm.tmin.latest.qcu.tar.gz"
V3.TMIN.ADJ.URL <- "ftp://ftp.ncdc.noaa.gov/pub/data/ghcn/v3/ghcnm.tmin.latest.qca.tar.gz" 
WATER.MASK.URL<-"http://www.drivehq.com/file/df.aspx/publish/stevenmosher/land_percent_qd.asc Publish/land_percent_qd.asc"   
OCEAN.MASK.URL<-"http://www.drivehq.com/file/df.aspx/publish/stevenmosher/land_percent2_qd.asc Publish/land_percent2_qd.asc"